apiVersion: v1
kind: Namespace
metadata:
  name: otel-demo
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-otel-demo
  namespace: otel-demo
  labels:
    app: python-otel-demo
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-otel-demo
  template:
    metadata:
      labels:
        app: python-otel-demo
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: python-otel-demo
        image: python-otel-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://signoz-otel-collector.observability.svc.cluster.local:4317"
        - name: SERVICE_NAME
          value: "python-otel-demo"
        - name: DEPLOYMENT_ENVIRONMENT
          value: "production"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: python-otel-demo
  namespace: otel-demo
  labels:
    app: python-otel-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: python-otel-demo
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: python-otel-demo-vs
  namespace: otel-demo
spec:
  hosts:
  - "python-demo.bocopile.io"
  gateways:
  - python-otel-demo-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: python-otel-demo
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: python-otel-demo-gw
  namespace: otel-demo
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "python-demo.bocopile.io"
