#cloud-config
runcmd:
  # ... (기존 runcmd 상단 생략)
  - bash -lc 'mkdir -p /backup/registry'
write_files:
  - path: /usr/local/bin/backup_registry.sh
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      set -euo pipefail
      TS=$(date +%Y%m%d-%H%M%S)
      SRC="/data/registry"
      DST="/backup/registry/${TS}"
      mkdir -p "$DST"
      rsync -a --delete "$SRC/" "$DST/"
      # 보존 7일
      find /backup/registry -mindepth 1 -maxdepth 1 -type d -mtime +6 -exec rm -rf {} \;
  - path: /etc/cron.d/backup-registry
    permissions: '0644'
    content: |
      # 매일 03:05에 실행
      5 3 * * * root /usr/local/bin/backup_registry.sh >/var/log/backup_registry.log 2>&1
