grafana:
  adminPassword: admin
  image:
    tag: "12.0.2"  # Grafana 버전 고정 (원하는 버전으로 변경 가능)
  ingress:
    enabled: false
  service:
    type: LoadBalancer
  ## Loki 데이터 소스 자동 등록
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          uid: loki
          access: proxy
          url: http://loki:3100
          isDefault: false
          version: 1
          editable: true
          jsonData:
            isdefault: false
            maxLines: 1000                    # 로그 조회 제한
            httpMethod: GET                   # GET 방식 사용 권장
prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
