apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cluster-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bocopile/terraform-k8s-mac.git
    targetRevision: HEAD
    path: argocd-apps/app-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
