apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - chart: base
        version: 1.20.0
        name: istio-base
      - chart: gateway
        version: 1.20.0
        name: istio-ingressgateway
  template:
    metadata:
      name: 'app-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://istio-release.storage.googleapis.com/charts
        targetRevision: '{{version}}'
        chart: '{{chart}}'
        helm:
          values: |
            # Remote cluster configuration
            # Connected to Control Cluster Istiod
      destination:
        server: https://app-cluster-api:6443
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
