apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.72.0
    chart: opentelemetry-collector
    helm:
      values: |
        mode: daemonset
        image:
          repository: otel/opentelemetry-collector-k8s
          tag: 0.88.0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        service:
          type: ClusterIP
          ports:
            otlp:
              enabled: true
              containerPort: 4317
              servicePort: 4317
              protocol: TCP
            otlp-http:
              enabled: true
              containerPort: 4318
              servicePort: 4318
              protocol: TCP
            jaeger-grpc:
              enabled: true
              containerPort: 14250
              servicePort: 14250
              protocol: TCP
            jaeger-thrift:
              enabled: true
              containerPort: 14268
              servicePort: 14268
              protocol: TCP
            zipkin:
              enabled: true
              containerPort: 9411
              servicePort: 9411
              protocol: TCP
            metrics:
              enabled: true
              containerPort: 8888
              servicePort: 8888
              protocol: TCP
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:14250
                thrift_http:
                  endpoint: 0.0.0.0:14268
            zipkin:
              endpoint: 0.0.0.0:9411
            k8s_cluster:
              auth_type: serviceAccount
              node_conditions_to_report:
                - Ready
                - MemoryPressure
              allocatable_types_to_report:
                - cpu
                - memory
          processors:
            batch:
              timeout: 10s
              send_batch_size: 1024
            memory_limiter:
              check_interval: 1s
              limit_mib: 400
            resource:
              attributes:
                - key: cluster
                  value: app-cluster
                  action: upsert
                - key: environment
                  value: production
                  action: upsert
            k8sattributes:
              auth_type: serviceAccount
              passthrough: false
              extract:
                metadata:
                  - k8s.namespace.name
                  - k8s.deployment.name
                  - k8s.statefulset.name
                  - k8s.daemonset.name
                  - k8s.cronjob.name
                  - k8s.job.name
                  - k8s.node.name
                  - k8s.pod.name
                  - k8s.pod.uid
                  - k8s.pod.start_time
                labels:
                  - tag_name: app
                    key: app.kubernetes.io/name
                    from: pod
                  - tag_name: version
                    key: app.kubernetes.io/version
                    from: pod
          exporters:
            otlp:
              endpoint: 192.168.64.105:4317
              tls:
                insecure: true
              sending_queue:
                num_consumers: 10
                queue_size: 1000
              retry_on_failure:
                enabled: true
                initial_interval: 5s
                max_interval: 30s
                max_elapsed_time: 300s
          service:
            telemetry:
              logs:
                level: info
              metrics:
                address: 0.0.0.0:8888
            pipelines:
              traces:
                receivers:
                  - otlp
                  - jaeger
                  - zipkin
                processors:
                  - memory_limiter
                  - k8sattributes
                  - resource
                  - batch
                exporters:
                  - otlp
        serviceAccount:
          create: true
          annotations: {}
        rbac:
          create: true
        clusterRole:
          create: true
          rules:
            - apiGroups:
                - ""
              resources:
                - events
                - namespaces
                - namespaces/status
                - nodes
                - nodes/spec
                - pods
                - pods/status
                - replicationcontrollers
                - replicationcontrollers/status
                - resourcequotas
                - services
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - apps
              resources:
                - daemonsets
                - deployments
                - replicasets
                - statefulsets
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - batch
              resources:
                - jobs
                - cronjobs
              verbs:
                - get
                - list
                - watch
        tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        nodeSelector: {}
        affinity: {}
        podSecurityContext:
          runAsUser: 0
          runAsGroup: 0
  destination:
    server: https://app-cluster-api:6443
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
