grafana:
  service:
    type: LoadBalancer
  ingress:
    enabled: false
  adminPassword: admin

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 7d
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}