apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-otel-demo
  namespace: otel-demo
  labels:
    app: java-otel-demo
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-otel-demo
  template:
    metadata:
      labels:
        app: java-otel-demo
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: java-otel-demo
        image: java-otel-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://signoz-otel-collector.observability.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "java-otel-demo"
        - name: OTEL_DEPLOYMENT_ENVIRONMENT
          value: "production"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: java-otel-demo
  namespace: otel-demo
  labels:
    app: java-otel-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: java-otel-demo
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: java-otel-demo-vs
  namespace: otel-demo
spec:
  hosts:
  - "java-demo.bocopile.io"
  gateways:
  - java-otel-demo-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: java-otel-demo
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: java-otel-demo-gw
  namespace: otel-demo
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "java-demo.bocopile.io"
