# ClusterIssuer Resources for cert-manager
# Provides certificate signing for all namespaces

---
# SelfSigned ClusterIssuer
# Used for bootstrap CA certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}

---
# CA ClusterIssuer (uses CA certificate from bootstrap)
# This is the primary issuer for service certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-cluster-issuer
spec:
  ca:
    secretName: ca-key-pair

---
# Bootstrap CA Certificate
# Creates the root CA certificate using SelfSigned issuer
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: cert-manager
spec:
  isCA: true
  commonName: bocopile.io
  secretName: ca-key-pair
  duration: 87600h  # 10 years
  renewBefore: 720h  # 30 days
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
# Istio Gateway Wildcard Certificate
# *.bocopile.io certificate for all services
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-cert
  namespace: istio-ingress
spec:
  secretName: istio-gateway-tls
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days (renew at 60 days remaining)
  commonName: "*.bocopile.io"
  dnsNames:
    - "*.bocopile.io"
    - bocopile.io
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: ca-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
