version: "3.9"
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
      # - "5000:5000"   # 필요 시 repository connector용
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms2g -Xmx4g -XX:MaxDirectMemorySize=4g"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /data/nexus-data:/nexus-data
