configs:
  secret:
    # admin
    argocdServerAdminPassword: $2y$12$2btfod59SWVmV09TuHabu.1j8Xq7kD3Pn7wF0zW9deziF0zHW9Soa

# High Availability: Controller 고가용성 설정
controller:
  replicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: application-controller
            topologyKey: kubernetes.io/hostname
  pdb:
    enabled: true
    minAvailable: 1

server:
  # High Availability: Server 고가용성 설정
  replicas: 2
  autoscaling:
    enabled: false
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: server
            topologyKey: kubernetes.io/hostname
  pdb:
    enabled: true
    minAvailable: 1
  ingress:
    enabled: false
  service:
    type: LoadBalancer

# High Availability: Repo Server 고가용성 설정
repoServer:
  replicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: repo-server
            topologyKey: kubernetes.io/hostname
  pdb:
    enabled: true
    minAvailable: 1

# High Availability: Application Set Controller 고가용성
applicationSet:
  replicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: applicationset-controller
            topologyKey: kubernetes.io/hostname
  pdb:
    enabled: true
    minAvailable: 1
