global:
  proxy:
    autoInject: enabled
  # Security: mTLS 강제 적용 (STRICT mode)
  mtls:
    enabled: true
  # Security: SecurityContext 설정
  securityContext:
    runAsUser: 1337
    runAsGroup: 1337
    runAsNonRoot: true
    fsGroup: 1337
    seccompProfile:
      type: RuntimeDefault
  # Distributed Tracing: SigNoz OTEL Collector 연동
  tracer:
    zipkin:
      address: signoz-otel-collector.observability.svc.cluster.local:9411
  # Envoy 트레이싱 설정
  proxy_init:
    image: proxyv2
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100.0  # 100% 샘플링 (개발/테스트용, 운영환경에서는 1-10% 권장)
        max_path_tag_length: 256
        zipkin:
          address: signoz-otel-collector.observability.svc.cluster.local:9411
    extensionProviders:
      - name: signoz
        zipkin:
          service: signoz-otel-collector.observability.svc.cluster.local
          port: 9411

gateways:
  istio-ingressgateway:
    type: LoadBalancer
    # High Availability: Ingress Gateway 복제본
    replicaCount: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: istio-ingressgateway
              topologyKey: kubernetes.io/hostname
    ports:
      - port: 80
        targetPort: 8080
        name: http
      - port: 443
        targetPort: 8443
        name: https
    serviceAnnotations: {}

pilot:
  # High Availability: Istiod (Control Plane) 복제본
  replicaCount: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: istiod
            topologyKey: kubernetes.io/hostname
  autoscaleEnabled: false