global:
  clusterName: local-multipass
  clickhouse:
    enabled: true
    persistence:
      enabled: true
      size: 50Gi
      storageClass: local-path

otelCollector:
  gateway:
    enabled: true
    # High Availability: 다중 게이트웨이로 SPOF 제거
    replicas: 2
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - otel-collector-gateway
              topologyKey: kubernetes.io/hostname
    service:
      type: ClusterIP
      ports:
        otlpGrpc: 4317
        otlpHttp: 4318
    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}
      processors:
        batch: {}
      exporters:
        clickhouse:
          endpoint: tcp://signoz-clickhouse:9000?dial_timeout=10s&compress=true
          database: signoz
          ttl_days: 15
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [clickhouse]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [clickhouse]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [clickhouse]

  agent:
    enabled: true
    # We primarily use Fluent Bit for logs; agent will scrape host/node/pod metrics if needed
    extraEnvs:
      - name: SIG_NOZ_CLUSTER
        value: local-multipass

frontend:
  # High Availability: 프론트엔드 복제본 증가
  replicas: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - frontend
            topologyKey: kubernetes.io/hostname
  service:
    type: ClusterIP

ingress:
  enabled: false  # we expose via Istio below

clickhouse:
  # High Availability: ClickHouse 클러스터 구성
  replicaCount: 2
  shards: 1
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: clickhouse
            topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

retentionPeriod:
  metrics: 15d
  traces: 15d
  logs: 7d
