server:
  # High Availability: 프로덕션 모드로 전환 (dev 모드는 SPOF)
  dev:
    enabled: false

  # HA 모드 설정: Raft 통합 스토리지 사용
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "http://vault-0.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-1.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-2.vault-internal:8200"
          }
        }

        service_registration "kubernetes" {}

  # Pod Disruption Budget
  podDisruptionBudget:
    enabled: true
    minAvailable: 2

  # Anti-affinity 설정
  affinity: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vault
                app.kubernetes.io/instance: vault
            topologyKey: kubernetes.io/hostname

  # 데이터 영속성
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: local-path

  # 감사 로그 영속성
  auditStorage:
    enabled: true
    size: 10Gi
    storageClass: local-path

  service:
    type: ClusterIP  # ISTIO_EXPOSE=on 모드에서 Istio Ingress Gateway를 통해 노출
    annotations:
      external-dns.alpha.kubernetes.io/hostname: vault.bocopile.io

ui:
  enabled: true